### ISSUE TITLE
Issues listing composer-dev available versions and isolation of local environment

### ISSUE THREAD

**Issue by Ch41r05** [GoogleCloudPlatform/composer-local-dev#36] opened 2024-02-13 11:13 UTC
# What I've done
I've been following [this guide](https://cloud.google.com/composer/docs/composer-2/run-local-airflow-environments?hl=it) to create a local airflow environment since I need to be able to test dags in a local environment without running them on the remote composer on the GCP. I opted for the Docker container approach, so i ran:

```
docker pull gcr.io/google.com/cloudsdktool/google-cloud-cli:latest
docker run --rm gcr.io/google.com/cloudsdktool/google-cloud-cli:latest gcloud version
docker run -ti --name gcloud-config gcr.io/google.com/cloudsdktool/google-cloud-cli gcloud auth login
git clone https://github.com/GoogleCloudPlatform/composer-local-dev.git
gcloud projects create your_project
docker run --rm --volumes-from gcloud-config gcr.io/google.com/cloudsdktool/google-cloud-cli gcloud compute instances list --project your_project
```

I've already authenticated with my gmail account and set GOOGLE_APPLICATION_CREDENTIALS and GOOGLE_CLOUD_PROJECT.

# The Error
When I run
```
composer-dev list-available-versions --include-past-releases --limit 10
```
I get the following error
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/composer_local_dev/errors.py", line 185, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/composer_local_dev/cli.py", line 594, in list_available_versions
    image_versions = utils.get_image_versions(
  File "/usr/local/lib/python3.9/dist-packages/composer_local_dev/utils.py", line 308, in get_image_versions
    page_result = client.list_image_versions(request=request)
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/orchestration/airflow/service_v1/services/image_versions/client.py", line 741, in list_image_versions
    self._validate_universe_domain()
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/orchestration/airflow/service_v1/services/image_versions/client.py", line 481, in _validate_universe_domain
    or ImageVersionsClient._compare_universes(
  File "/usr/local/lib/python3.9/dist-packages/google/cloud/orchestration/airflow/service_v1/services/image_versions/client.py", line 458, in _compare_universes
    credentials_universe = credentials.universe_domain
AttributeError: 'Credentials' object has no attribute 'universe_domain'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/composer-dev", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/rich_click/rich_group.py", line 21, in main
    return super().main(*args, standalone_mode=False, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/composer_local_dev/errors.py", line 195, in wrapper
    raise ComposerCliFatalError(message)
composer_local_dev.errors.ComposerCliFatalError:
Fatal exception occurred. Please report at https://github.com/GoogleCloudPlatform/composer-local-dev/issues
```

Also, when running
```
gcloud info
```
I also get the projects I have on cloud listed and the previous your_project was created on cloud.
Is there a way to have it as a separate local environment?

# Expected Behaviour
Composer dev available version list should correctly appear and the environment should be an isolated local environment.

**Comment by nbonnotte** [comment] 2024-02-14 08:58
Duplicate of #32 and #33

You can upgrade library `google-auth` to `2.27.*`

**Closed** 2024-03-12 14:03 UTC
